version: "3.9"
services:
  apache:
    image: httpd:alpine
    volumes:
      - ../public_html:/var/www/html
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - 8080:80
    depends_on:
      - php

  php:
    depends_on:
      - db
      - phpmyadmin
      - redis
    image: php-fpm
    build:
      context: php
      dockerfile: fpm-alpine/Dockerfile
    restart: always
    volumes:
      - ../public_html:/var/www/html
      - ./docker-fpm.ini:/usr/local/etc/php/conf.d/docker-fpm.ini
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      REDIS_HOST: redis
    ports:
      - 9000:9000

  db:
    image: mariadb
    container_name: db
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      SKIP_INNODB: yes
    ports:
      - 3306:3306

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: phpmyadmin
    restart: always
    ports:
      - 8180:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
      UPLOAD_LIMIT: 300M

  redis:
    image: redis:7.2.4
    container_name: redis
    restart: always
    ports:
      - 6379:6379
